// CREATE TABLE IF NOT EXISTS furniture (
//   furniture_id INTEGER PRIMARY KEY AUTOINCREMENT,
//   furniture_name TEXT NOT NULL,
//   furniture_description TEXT NOT NULL,
//   sale_price INTEGER NOT NULL,
//   resale_price INTEGER NOT NULL,
//   quantity_owned INTEGER NOT NULL,
//   happiness_buff REAL NOT NULL,
//   energy_buff REAL NOT NULL
// );


typedef DecorationIcon = ({
  String name,
  String description,
  String imagePath,
  int salePrice,
  int resalePrice,
  int happinessBuff,
  int energyBuff,
  bool isFacingLeft,
});

const Map<String, DecorationIcon> decorationIcons = <String, DecorationIcon>{
  "blue_table": (
    name: "Blue Leather Table",
    description: "A Blue Leather Table.",
    imagePath: "assets/images/furniture/blue_table.png",
    salePrice: 150,
    resalePrice: 250,
    happinessBuff: 100,
    energyBuff: 50,
    isFacingLeft: false,
  ),
  "burgundy_drawer": (
    name: "Burgundy Oak Drawer",
    description: "A glossy burgundy oak drawer.",
    imagePath: "assets/images/furniture/burgundy_drawer.png",
    salePrice: 100,
    resalePrice: 200,
    happinessBuff: 100,
    energyBuff: 60,
    isFacingLeft: false,
  ),
  "round_glass_table": (
    name: "Round Glass Table",
    description: "A glossy burgundy oak drawer.",
    imagePath: "assets/images/furniture/round_glass_table.png",
    salePrice: 250,
    resalePrice: 400,
    happinessBuff: 150,
    energyBuff: 60,
    isFacingLeft: false,
  ),
  "black_steel_chair": (
    name: "Black Steel Chair",
    description: "A black steel chair.",
    imagePath: "assets/images/furniture/black_steel_chair.png",
    salePrice: 75,
    resalePrice: 150,
    happinessBuff: 80,
    energyBuff: 40,
    isFacingLeft: false,
  ),
  "mocha_couch": (
    name: "Mocha Couch",
    description: "a soft, fancy, mocha couch.",
    imagePath: "assets/images/furniture/mocha_couch.png",
    salePrice: 250,
    resalePrice: 450,
    happinessBuff: 150,
    energyBuff: 100,
    isFacingLeft: false,
  ),
  "mocha_office_chair": (
    name: "Mocha Ergonomic Chair",
    description: "A ergonomic mocha chair.",
    imagePath: "assets/images/furniture/mocha_office_chair.png",
    salePrice: 250,
    resalePrice: 450,
    happinessBuff: 150,
    energyBuff: 100,
    isFacingLeft: false,
  ),
  "mocha_kitchen_chair": (
    name: "Mocha Kitchen Chair",
    description: "A kitchen mocha chair.",
    imagePath: "assets/images/furniture/mocha_kitchen_chair.png",
    salePrice: 250,
    resalePrice: 450,
    happinessBuff: 150,
    energyBuff: 100,
    isFacingLeft: false,
  ),
  "kitchen_stove": (
    name: "Kitchen Stove",
    description: "A steelware kitchen stove.",
    imagePath: "assets/images/furniture/kitchen_stove.png",
    salePrice: 100,
    resalePrice: 200,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
  ),
  "melamine_bookshelf": (
    name: "Bookshelf",
    description: "A melamine bookshelf.",
    imagePath: "assets/images/furniture/melamine_bookshelf.png",
    salePrice: 100,
    resalePrice: 200,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: true,
  ),
  "kitchen_drawer": (
    name: "Kitchen Drawer",
    description: "A kitchen drawer.",
    imagePath: "assets/images/furniture/kitchen_drawer.png",
    salePrice: 100,
    resalePrice: 200,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
  ),

  /// [key: id]: FurnitureIcon.
};
