// CREATE TABLE IF NOT EXISTS furniture (
//   furniture_id INTEGER PRIMARY KEY AUTOINCREMENT,
//   furniture_name TEXT NOT NULL,
//   furniture_description TEXT NOT NULL,
//   sale_price INTEGER NOT NULL,
//   resale_price INTEGER NOT NULL,
//   quantity_owned INTEGER NOT NULL,
//   happiness_buff REAL NOT NULL,
//   energy_buff REAL NOT NULL
// );

import "package:happy_habit_at/constants/decoration_category.dart";
import "package:happy_habit_at/structs/display_offset.dart";
import "package:happy_habit_at/utils/extension_types/ids.dart";

typedef DecorationIcon = ({
  String name,
  String description,
  String imagePath,
  int salePrice,
  int resalePrice,
  int happinessBuff,
  int energyBuff,
  bool isFacingLeft,

  // Technical values
  (double width, double height) imageDimensions,
  DecorationCategory category,
  DisplayOffset displayOffset,
});

const Map<DecorationId, DecorationIcon> decorationIcons = <DecorationId, DecorationIcon>{
  DecorationId("blue_table"): (
    name: "Blue Leather Table",
    description: "A Blue Leather Table.",
    imagePath: "assets/images/furniture/blue_table.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 50,
    isFacingLeft: false,
    imageDimensions: (42.0, 42.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (6, -5),
      flippedOffset: (3, -5),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("burgundy_drawer"): (
    name: "Burgundy Oak Drawer",
    description: "A glossy burgundy oak drawer.",
    imagePath: "assets/images/furniture/burgundy_drawer.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 60,
    isFacingLeft: false,
    imageDimensions: (56.0, 64.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (1, -36),
      flippedOffset: (-4, -36),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("round_glass_table"): (
    name: "Round Glass Table",
    description: "A glossy burgundy oak drawer.",
    imagePath: "assets/images/furniture/round_glass_table.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 150,
    energyBuff: 60,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -11),
      flippedOffset: (4, -11),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("black_steel_chair"): (
    name: "Black Steel Chair",
    description: "A black steel chair.",
    imagePath: "assets/images/furniture/black_steel_chair.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 80,
    energyBuff: 40,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (5, -15),
      flippedOffset: (5, -15),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("mocha_couch"): (
    name: "Mocha Couch",
    description: "a soft, fancy, mocha couch.",
    imagePath: "assets/images/furniture/mocha_couch.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 150,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (56.0, 64.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (1, -36),
      flippedOffset: (-4, -36),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("mocha_office_chair"): (
    name: "Mocha Ergonomic Chair",
    description: "A ergonomic mocha chair.",
    imagePath: "assets/images/furniture/mocha_office_chair.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 150,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -19),
      flippedOffset: (4, -19),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("mocha_kitchen_chair"): (
    name: "Mocha Kitchen Chair",
    description: "A kitchen mocha chair.",
    imagePath: "assets/images/furniture/mocha_kitchen_chair.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 150,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -19),
      flippedOffset: (4, -19),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("kitchen_stove"): (
    name: "Kitchen Stove",
    description: "A steelware kitchen stove.",
    imagePath: "assets/images/furniture/kitchen_stove.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (56.0, 64.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (1, -36),
      flippedOffset: (-4, -36),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("melamine_bookshelf"): (
    name: "Bookshelf",
    description: "A melamine bookshelf.",
    imagePath: "assets/images/furniture/melamine_bookshelf.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: true,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("kitchen_drawer"): (
    name: "Kitchen Drawer",
    description: "A kitchen drawer.",
    imagePath: "assets/images/furniture/kitchen_drawer.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (56.0, 64.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (1, -36),
      flippedOffset: (-4, -36),
      baseOffset: (0, 0),
    ),
  ),
//   // nature decorations
//   //yellow autumn tree classifications
  DecorationId("bigytree1"): (
    name: "Tall Autumn Tree",
    description: "A stripped tall autumn tree.",
    imagePath: "assets/images/trees/bigytree1.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 92.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -36),
      flippedOffset: (-8, -36),
      baseOffset: (-1, -1),
    ),
  ),

  DecorationId("bigytree2"): (
    name: "Big Autumn Tree",
    description: "A Full autumn tree.",
    imagePath: "assets/images/trees/bigytree2.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("bigytree3"): (
    name: "Round Short Autumn Tree",
    description: "A short rounded autumn tree.",
    imagePath: "assets/images/trees/bigytree3.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -14),
      flippedOffset: (4, -14),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("bigytree4"): (
    name: "Tall Coned Autumn Tree",
    description: "A Tall coned autumn tree.",
    imagePath: "assets/images/trees/bigytree4.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("bigytree5"): (
    name: "Tall Round Autumn Tree",
    description: "A tall rounded autumn tree.",
    imagePath: "assets/images/trees/bigytree5.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("bigytree6"): (
    name: "Tall Rounded Yellow Tree",
    description: "A tall rounded yellow tree.",
    imagePath: "assets/images/trees/bigytree6.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("bigytree7"): (
    name: "Big Rounded Yellow Tree",
    description: "A big crounded yellow tree.",
    imagePath: "assets/images/trees/bigytree7.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("bigytree8"): (
    name: "Single Rounded Yellow Tree",
    description: "A single rounded yellow tree.",
    imagePath: "assets/images/trees/bigytree8.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  //bushes
  DecorationId("bush1"): (
    name: "Upper Arrowed Bush",
    description: "A upper arrowed green bush.",
    imagePath: "assets/images/bush/bush1.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (5, -10),
      flippedOffset: (5, -10),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("bush2"): (
    name: "Left Arrowed Bush",
    description: "A left arrowed green bush.",
    imagePath: "assets/images/bush/bush2.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (0, -10),
      flippedOffset: (0, -10),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("bush3"): (
    name: "Right Arrowed Bush",
    description: "A right arrowed green bush.",
    imagePath: "assets/images/bush/bush3.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (10, -10),
      flippedOffset: (10, -10),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("bush4"): (
    name: "Down Arrowed Bush",
    description: "A down arrowed green bush.",
    imagePath: "assets/images/bush/bush4.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (5, -4),
      flippedOffset: (5, -4),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("bush5"): (
    name: "Left Facing Bush",
    description: "A left faced green bush.",
    imagePath: "assets/images/bush/bush5.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (5, -8),
      flippedOffset: (5, -8),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("bush6"): (
    name: "Single Pillar Bush",
    description: "A single pillared green bush.",
    imagePath: "assets/images/bush/bush6.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -10),
      flippedOffset: (3, -10),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("bush7"): (
    name: "Right Pillar Bush",
    description: "A right faced green bush.",
    imagePath: "assets/images/bush/bush7.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (8, -5),
      flippedOffset: (8, -5),
      baseOffset: (0, 0),
    ),
  ),
  //yellow bushes
  DecorationId("ybush1"): (
    name: "Upper Arrowed Yellow Bush",
    description: "A upper arrowed yellow bush.",
    imagePath: "assets/images/bush/ybush1.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (5, -8),
      flippedOffset: (5, -8),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ybush2"): (
    name: "Left Arrowed Yellow Bush",
    description: "A left arrowed yelliw bush.",
    imagePath: "assets/images/bush/ybush2.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (0, -10),
      flippedOffset: (0, -10),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ybush3"): (
    name: "Right Arrowed Yellow Bush",
    description: "A right arrowed green bush.",
    imagePath: "assets/images/bush/ybush3.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (10, -10),
      flippedOffset: (10, -10),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ybush4"): (
    name: "Down Arrowed Yellow Bush",
    description: "A down arrowed yellow bush.",
    imagePath: "assets/images/bush/ybush4.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (5, -4),
      flippedOffset: (5, -4),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ybush5"): (
    name: "Left Facing Yellow Bush",
    description: "A left faced yellow bush.",
    imagePath: "assets/images/bush/ybush5.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (5, -8),
      flippedOffset: (5, -8),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ybush6"): (
    name: "Single Pillar Yellow Bush",
    description: "A single pillared yellow bush.",
    imagePath: "assets/images/bush/ybush6.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -10),
      flippedOffset: (3, -10),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ybush7"): (
    name: "Right Facing Yellow Bush",
    description: "A right faced yellow bush.",
    imagePath: "assets/images/bush/bush7.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (8, -5),
      flippedOffset: (8, -5),
      baseOffset: (0, 0),
    ),
  ),
  // yellow trees
  DecorationId("ytree"): (
    name: "Short Boxed Yellow Tree",
    description: "A short boxed yellow tree.",
    imagePath: "assets/images/trees/ytree.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ytree1"): (
    name: "Tall Rounded Yellow Tree",
    description: "A tall skinny coned yellow tree.",
    imagePath: "assets/images/trees/ytree1.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("ytree2"): (
    name: "Tall Hickory Yellow Tree",
    description: "A tall hickory yellow tree.",
    imagePath: "assets/images/trees/ytree2.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("ytree3"): (
    name: "Tall Fir Yellow Tree",
    description: "A tall fir yellow tree.",
    imagePath: "assets/images/trees/ytree3.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("ytree4"): (
    name: "Short Pine Yellow Tree",
    description: "A short pine yellow tree.",
    imagePath: "assets/images/trees/ytree4.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ytree5"): (
    name: "Short cylinderical Yellow Tree",
    description: "A short cylindrical yellow tree.",
    imagePath: "assets/images/trees/ytree5.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ytree6"): (
    name: "Short Columnar Yellow Tree",
    description: "A short columnar yellow tree.",
    imagePath: "assets/images/trees/ytree6.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ytree7"): (
    name: "Short Elm Yellow Tree",
    description: "A short elm yellow tree.",
    imagePath: "assets/images/trees/ytree7.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ytree8"): (
    name: "Short Pine Boxed Yellow Tree",
    description: "A short pine boxed yellow tree.",
    imagePath: "assets/images/trees/ytree8.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ytree9"): (
    name: "Tall Spruce Yellow Tree",
    description: "A tall spruced yellow tree.",
    imagePath: "assets/images/trees/ytree9.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  //ntree
  DecorationId("ntree1"): (
    name: "Short Boxed Lime Tree",
    description: "A short boxed lime tree.",
    imagePath: "assets/images/trees/ntree1.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ntree2"): (
    name: "Short Spruce Lime Tree",
    description: "A short spruced lime tree.",
    imagePath: "assets/images/trees/ntree2.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ntree3"): (
    name: "Short Pine Lime Tree",
    description: "A short pine lime tree.",
    imagePath: "assets/images/trees/ntree3.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ntree4"): (
    name: "Medium Boxed Lime Tree",
    description: "A medium boxed lime tree.",
    imagePath: "assets/images/trees/ntree4.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ntree5"): (
    name: "Medium Pine Lime Tree",
    description: "A mediume pined lime tree.",
    imagePath: "assets/images/trees/ntree5.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("ntree6"): (
    name: "Tall Boxed Lime Tree",
    description: "A tall boxed lime tree.",
    imagePath: "assets/images/trees/ntree6.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("ntree7"): (
    name: "Tall Rounded Lime Tree",
    description: "A  tall rounded lime tree.",
    imagePath: "assets/images/trees/ntree7.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("ntree8"): (
    name: "Short Pyramidal Lime Tree",
    description: "A short pyramidal lime tree.",
    imagePath: "assets/images/trees/ntree8.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  //greentrees
  DecorationId("talltree"): (
    name: "Tall Green Tree",
    description: "A tall coned green tree.",
    imagePath: "assets/images/trees/talltree.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("tree1"): (
    name: "Short Boxed Green Tree",
    description: "A short boxed green tree.",
    imagePath: "assets/images/trees/tree1.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("tree2"): (
    name: "Tall Rounded Spruce Tree",
    description: "A tall spruce tree.",
    imagePath: "assets/images/trees/tree2.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("tree3"): (
    name: "Short Pine Tree",
    description: "A short pine tree.",
    imagePath: "assets/images/trees/tree3.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (3, -18),
      flippedOffset: (3, -18),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("tree4"): (
    name: "Palm Tree",
    description: "A Palm tree.",
    imagePath: "assets/images/trees/tree4.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 72.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("tree5"): (
    name: "Tall Palm Tree",
    description: "A tall palm tree.",
    imagePath: "assets/images/trees/tree5.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("tree6"): (
    name: "Short Box Pine Tree",
    description: "A short boxed pine tree.",
    imagePath: "assets/images/trees/tree6.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -16),
      flippedOffset: (4, -16),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("tree7"): (
    name: "Short Pine Tree",
    description: "A short pine tree.",
    imagePath: "assets/images/trees/tree7.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -16),
      flippedOffset: (4, -16),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("tree8"): (
    name: "Tall Rounded Tree",
    description: "A Tall rounded tree.",
    imagePath: "assets/images/trees/tree8.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("tree9"): (
    name: "Short Rounded Tree",
    description: "A short rounded tree.",
    imagePath: "assets/images/trees/tree9.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -16),
      flippedOffset: (4, -16),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("tree10"): (
    name: "Short Single Rounded Tree",
    description: "A short single round tree.",
    imagePath: "assets/images/trees/tree10.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -16),
      flippedOffset: (4, -16),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("tree11"): (
    name: "Tall Yellow Green Tree",
    description: "A tall yellow green tree.",
    imagePath: "assets/images/trees/tree11.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
  DecorationId("tree12"): (
    name: "Tall Hemlock Tree",
    description: "A tall hemlock tree.",
    imagePath: "assets/images/trees/tree12.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (64.0, 96.0),
    category: DecorationCategory.nature,
    displayOffset: DisplayOffset(
      defaultOffset: (-8, -12),
      flippedOffset: (-8, -12),
      baseOffset: (-2, -2),
    ),
  ),
//extras
  DecorationId("butterfly"): (
    name: "Butterflies",
    description: "A beautiful set of butterflies.",
    imagePath: "assets/images/extras/butterfly.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.camping,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -16),
      flippedOffset: (4, -16),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("chair"): (
    name: "Camping Chair",
    description: "A camping chair.",
    imagePath: "assets/images/extras/chair.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 42.0),
    category: DecorationCategory.camping,
    displayOffset: DisplayOffset(
      defaultOffset: (6, -5),
      flippedOffset: (3, -5),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("cooking"): (
    name: "Cooking Pot",
    description: "A cooking pot.",
    imagePath: "assets/images/extras/cooking.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.camping,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -14),
      flippedOffset: (4, -14),
      baseOffset: (0, 0),
    ),
  ),
  DecorationId("map"): (
    name: "Explorer Map",
    description: "An explorer map.",
    imagePath: "assets/images/extras/map.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 42.0),
    category: DecorationCategory.camping,
    displayOffset: DisplayOffset(
      defaultOffset: (6, 0),
      flippedOffset: (3, 0),
      baseOffset: (0, 0),
    ),
  ),

  DecorationId("sign"): (
    name: "Sign",
    description: "A sign.",
    imagePath: "assets/images/extras/sign.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (56.0, 64.0),
    category: DecorationCategory.furniture,
    displayOffset: DisplayOffset(
      defaultOffset: (1, -36),
      flippedOffset: (-4, -36),
      baseOffset: (0, 0),
    ),
  ),

  DecorationId("tent"): (
    name: "Tent",
    description: "A cozy tent to stay.",
    imagePath: "assets/images/extras/tent.png",
    salePrice: 150,
    resalePrice: 100,
    happinessBuff: 100,
    energyBuff: 100,
    isFacingLeft: false,
    imageDimensions: (42.0, 48.0),
    category: DecorationCategory.camping,
    displayOffset: DisplayOffset(
      defaultOffset: (4, -2),
      flippedOffset: (4, -2),
      baseOffset: (0, 0),
    ),
  ),

  /// [key: id]: FurnitureIcon.
};
